using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Windows.Forms;

[assembly: InternalsVisibleTo("DpiLayoutTests")]
namespace OpenCompositeConfigurator;

internal static class DpiLayout
{
    // Keep logical design coordinates immutable. DPI transitions and fitting must
    // never multiply a previously scaled/anchored layout.
    private sealed record Item(Control Control, Rectangle Bounds, Padding Margin,
        Padding Padding, Size Minimum, Size Maximum, string Family, float Points,
        FontStyle Style, float[]? Columns, float[]? Rows);
    private sealed class FitState
    {
        internal bool Scroll, Busy, Queued, MonitorFit;
        internal float Scale = 1f;
        internal float RequestedScale = 1f;
        internal Rectangle Area;
        internal Size Design;
        internal readonly Dictionary<Control, Item> Items = new();
        internal readonly Dictionary<(string, float, FontStyle), Font> Fonts = new();
    }

    internal static void Popup(Form form, Size? minimumContent = null)
    {
        form.PerformLayout();
        Size design = minimumContent ?? form.ClientSize;
        var state = new FitState { Scroll = minimumContent.HasValue };
        form.SuspendLayout();
        form.AutoSize = false;
        // The coordinator owns bounds and font scaling. Windows still supplies
        // per-monitor DPI and native font metrics; do not also autoscale this tree.
        form.AutoScaleMode = AutoScaleMode.None;
        var content = new Panel { Name = "DpiContent", Size = form.ClientSize,
            BackColor = form.BackColor, Margin = Padding.Empty, Tag = state };
        var children = form.Controls.Cast<Control>().ToArray();
        foreach (Control child in children) content.Controls.Add(child);
        for (int i = 0; i < children.Length; ++i) content.Controls.SetChildIndex(children[i], i);
        form.Controls.Add(content);
        form.AutoScroll = state.Scroll;
        Capture(content, state);
        form.ResumeLayout(true);
        void Fit(bool keepSize = false)
        {
            if (!form.IsDisposed && !form.Disposing)
                FitPopup(form, content, design, Screen.FromControl(form).WorkingArea, form.DeviceDpi / 96f, keepSize);
        }
        void QueueFit(bool monitor = true)
        {
            state.MonitorFit |= monitor;
            if (state.Queued || !form.IsHandleCreated || form.Disposing) return;
            state.Queued = true;
            form.BeginInvoke((Action)(() =>
            {
                state.Queued = false;
                bool monitorFit = state.MonitorFit; state.MonitorFit = false;
                if (form.IsDisposed || form.Disposing) return;
                if (monitorFit) Fit(); else Refresh(form);
            }));
        }
        foreach (Control c in LayoutControls(content).Where(c => c is Panel or UserControl))
            c.VisibleChanged += (_, _) =>
            {
                if (!c.Visible || state.Busy || state.Queued || !form.IsHandleCreated || form.Disposing) return;
                QueueFit(false);
            };
        // Follow the client rectangle during resizing, including snap and
        // maximize/restore. Re-fitting to the monitor here would undo the size
        // the user just chose. Ignore events generated by our own layout pass.
        form.ClientSizeChanged += (_, _) =>
        {
            if (state.Busy || form.WindowState == FormWindowState.Minimized) return;
            QueueFit(false);
        };
        form.Shown += (_, _) => Fit();
        form.ResizeEnd += (_, _) => Fit(true);
        form.DpiChanged += (_, _) => QueueFit();
        form.Disposed += (_, _) => { foreach (Font font in state.Fonts.Values) font.Dispose(); };
    }

    private static void Capture(Control root, FitState state)
    {
        foreach (Control c in LayoutControls(root))
        {
            if (state.Items.ContainsKey(c)) continue;
            if (c is ContainerControl container) container.AutoScaleMode = AutoScaleMode.None;
            var table = c as TableLayoutPanel;
            state.Items.Add(c, new(c, c.Bounds, c.Margin, c.Padding, c.MinimumSize, c.MaximumSize,
                c.Font.FontFamily.Name, c.Font.SizeInPoints, c.Font.Style,
                table?.ColumnStyles.Cast<ColumnStyle>().Select(s => s.SizeType == SizeType.Absolute ? s.Width : -1).ToArray(),
                table?.RowStyles.Cast<RowStyle>().Select(s => s.SizeType == SizeType.Absolute ? s.Height : -1).ToArray()));
        }
    }

    internal static void FitPopup(Form form, Panel content, Size design, Rectangle area, float scale, bool keepSize = false)
    {
        var state = (FitState)content.Tag!;
        if (form.IsDisposed || state.Busy || form.WindowState == FormWindowState.Minimized) return;
        state.Busy = true;
        state.Area = area; state.Design = design; state.RequestedScale = scale;
        var controls = LayoutControls(content).ToArray();
        form.SuspendLayout();
        foreach (Control c in controls) c.SuspendLayout();
        try
        {
            bool maximized = form.WindowState == FormWindowState.Maximized;
            form.AutoScrollPosition = Point.Empty;
            form.MinimumSize = Size.Empty;
            var actualClient = ClientArea(form);
            int borderWidth = Math.Max(0, form.Width - actualClient.Width);
            int borderHeight = Math.Max(0, form.Height - actualClient.Height);
            int availableWidth = Math.Max(1, area.Width - borderWidth);
            int availableHeight = Math.Max(1, area.Height - borderHeight);
            float fit = Math.Min(scale, Math.Min((float)availableWidth / design.Width, (float)availableHeight / design.Height));
            if (!maximized && !keepSize)
                form.Size = new Size(borderWidth + Math.Max(1, (int)Math.Floor(design.Width * fit)), borderHeight + Math.Max(1, (int)Math.Floor(design.Height * fit)));
            else if (!maximized)
                form.Size = new Size(borderWidth + Math.Min(actualClient.Width, availableWidth), borderHeight + Math.Min(actualClient.Height, availableHeight));
            // ClientSize can retain the requested dimensions when Windows caps
            // an oversized window. Use the real native client rectangle for fitting.
            actualClient = ClientArea(form);
            float layoutScale = state.Scroll ? scale : Math.Min(scale,
                Math.Min((float)actualClient.Width / design.Width, (float)actualClient.Height / design.Height));
            Apply(controls, state, layoutScale, form.DeviceDpi / 96f);
            foreach (Control disposed in state.Items.Keys.Where(c => c.IsDisposed).ToArray()) state.Items.Remove(disposed);
            var usedFonts = state.Items.Keys.Select(c => c.Font).ToHashSet();
            foreach (var key in state.Fonts.Keys.Where(k => !usedFonts.Contains(state.Fonts[k])).ToArray())
            {
                state.Fonts[key].Dispose(); state.Fonts.Remove(key);
            }
            state.Scale = layoutScale;
            content.Location = Point.Empty;
            content.Size = state.Scroll
                ? new Size(Math.Max(actualClient.Width, (int)Math.Ceiling(design.Width * scale)), Math.Max(actualClient.Height, (int)Math.Ceiling(design.Height * scale)))
                : actualClient;
            form.AutoScrollMinSize = state.Scroll ? content.Size : Size.Empty;
            if (!maximized)
                form.Location = new Point(Math.Clamp(form.Left, area.Left, Math.Max(area.Left, area.Right - form.Width)),
                    Math.Clamp(form.Top, area.Top, Math.Max(area.Top, area.Bottom - form.Height)));
        }
        finally
        {
            foreach (Control c in controls.Reverse()) c.ResumeLayout(true);
            form.ResumeLayout(true);
            state.Busy = false;
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct NativeRect { internal int Left, Top, Right, Bottom; }
    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static extern bool GetClientRect(IntPtr window, out NativeRect rect);
    private static Size ClientArea(Form form) => form.IsHandleCreated && GetClientRect(form.Handle, out var rect)
        ? new Size(rect.Right - rect.Left, rect.Bottom - rect.Top) : form.ClientSize;

    internal static void Refresh(Form form)
    {
        if (form.Controls["DpiContent"] is Panel content && content.Tag is FitState state && state.Design.Width > 0)
            FitPopup(form, content, state.Design, state.Area, state.RequestedScale, true);
    }

    private static void Apply(IEnumerable<Control> controls, FitState state, float scale, float deviceScale)
    {
        int S(int n) => (int)Math.Round(n * scale);
        Size Z(Size z) => new(S(z.Width), S(z.Height));
        Padding P(Padding p) => new(S(p.Left), S(p.Top), S(p.Right), S(p.Bottom));
        foreach (Control c in controls)
        {
            if (c.IsDisposed || !state.Items.TryGetValue(c, out Item? item)) continue;
            if (c is ModernCheckBox checkBox) checkBox.LayoutScale = scale;
            if (c is ModernRadioButton radioButton) radioButton.LayoutScale = scale;
            float points = Math.Max(1f, item.Points * scale / deviceScale);
            var key = (item.Family, points, c.Font.Style);
            if (!state.Fonts.TryGetValue(key, out Font? font))
                state.Fonts[key] = font = new Font(item.Family, points, c.Font.Style);
            c.Font = font;
            c.Margin = P(item.Margin); c.Padding = P(item.Padding);
            c.MinimumSize = Z(item.Minimum); c.MaximumSize = Z(item.Maximum);
            if (c is TableLayoutPanel table)
            {
                for (int i = 0; i < item.Columns!.Length; ++i)
                    if (item.Columns[i] >= 0) table.ColumnStyles[i].Width = item.Columns[i] * scale;
                for (int i = 0; i < item.Rows!.Length; ++i)
                    if (item.Rows[i] >= 0) table.RowStyles[i].Height = item.Rows[i] * scale;
            }
            c.SetBounds(S(item.Bounds.X), S(item.Bounds.Y), S(item.Bounds.Width), S(item.Bounds.Height));
        }
    }

    // Late-created cards also start in logical coordinates and join the same
    // baseline so changing monitor does not double-scale them.
    internal static void AddLogicalControl(Control parent, Control child)
    {
        var content = parent.FindForm()?.Controls["DpiContent"] as Panel;
        if (content?.Tag is FitState state)
        {
            Capture(child, state);
            var controls = LayoutControls(child).ToArray();
            foreach (Control c in controls) c.SuspendLayout();
            parent.Controls.Add(child);
            Apply(controls, state, state.Scale, parent.DeviceDpi / 96f);
            foreach (Control c in controls.Reverse()) c.ResumeLayout(true);
        }
        else parent.Controls.Add(child);
    }

    private static IEnumerable<Control> LayoutControls(Control root)
    {
        yield return root;
        // Native composite inputs own their edit/spin windows. Do not resize or
        // assign fonts to those internals independently of their parent widget.
        if (root is UpDownBase or ComboBox or TextBoxBase) yield break;
        foreach (Control child in root.Controls)
            foreach (Control nested in LayoutControls(child)) yield return nested;
    }
}
